/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductListItemDto } from '../../models/product-list-item-dto';

export interface ApiCatalogProductsGet$Params {
}

export function apiCatalogProductsGet(http: HttpClient, rootUrl: string, params?: ApiCatalogProductsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductListItemDto>>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogProductsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductListItemDto>>;
    })
  );
}

apiCatalogProductsGet.PATH = '/api/catalog/products';
