/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponse {
  accessToken?: string | null;
  email?: string | null;
  refreshToken?: string | null;
  role?: string | null;
}
