/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { LoginRequest } from './models/login-request';
export type { RegisterRequest } from './models/register-request';
