/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ProductDetailDto } from './models/product-detail-dto';
export type { ProductListItemDto } from './models/product-list-item-dto';
