/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductListItemDto {
  brand?: string | null;
  id?: number;
  name?: string | null;
  price?: number;
}
