/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductUpdateDto {
  brand?: string | null;
  description?: string | null;
  name?: string | null;
  price?: number;
}
